   subroutine sub_wtmp_Ficklin
   !incomming
   !!  inum1         |none          |subbasin number
   !!hru_sub

   !local
   !!sb          |none          |subbasin number
   !!sub_wtmp(sb)             |C, temporary water temperature
   !!phru                        |, index of hru (ihru was used in "parm")


   use parm
     use parm_subC
        use parm_subE
        use parm_subH
        use parm_rchC
        use parm_rchE
        use parm_control
        use parm_output
   implicit none
   
   integer:: sb,phru
   integer:: wtmp_lag,iwtmpset,datefrom,dateto,plag
   real :: gwtmp_ann
   real :: wtmp_alpha       ! alpha   snowmelt water temperature     0.1
   real :: wtmp_mu          ! mu    ground water temperature   
   real :: wtmp_gamma       ! gamma                1.   
   real :: wtmp_beta        ! beta           K     0.25 
   real :: wtmp_eta         ! eta            e      0. 
   real :: tmpav_lag_mean
   real :: sub_suro_snowmelt

   sb=inum1

!see subwq for 0.0001
!if(sub_wyld(sb)<0.000001) then
 !  sub_wtmp(sb) = 5.0 + 0.75 * tmpav(hru1(sb))
 !  if (sub_wtmp(sb) <-1.0) sub_wtmp(sb) = -1.0
    !sub_wtmp_Ficklin = sub_wtmp(sb)
   ! return
!end if

!locate the set of parameter to be used
!do iwtmpset=1,wtmpset(sb)
   do iwtmpset=1,3
    datefrom = wtmppara(sb,iwtmpset,1)
    dateto = wtmppara(sb,iwtmpset,2)
    if(iida>=datefrom.AND.iida<=dateto) exit
   end do
!if the input date range is not closed (not from 1 to 366)
!if(iwtmpset>wtmpset(sb))      iwtmpset=wtmpset(sb)
  
!fill parameters
  wtmp_alpha = wtmppara(sb,iwtmpset,3)      ! alpha   snowmelt water temperature     0.1
  wtmp_mu = wtmppara(sb,iwtmpset,4)         ! mu      ground water temperature   
  wtmp_gamma = wtmppara(sb,iwtmpset,5)      ! gamma                 1.   
  wtmp_beta = wtmppara(sb,iwtmpset,6)       ! beta           K      0.25 
  wtmp_eta = wtmppara(sb,iwtmpset,7)        ! eta            e      0. 
  wtmp_lag = wtmppara(sb,iwtmpset,8)        ! lag                   7

!wtmp_alpha = wtmp_alpha_ga
!wtmp_mu = wtmp_mu_ga
!wtmp_gamma = wtmp_gamma_ga
!wtmp_beta = wtmp_beta_ga
!wtmp_eta = wtmp_eta_ga
!wtmp_lag = wtmp_lag_ga

!calculate lagged average Tair

   tmpav_lag_mean=0.
   do plag = 1, wtmp_lag
   tmpav_lag_mean = tmpav_lag_mean + tmpav_lag(plag,sb)
   end do
   tmpav_lag_mean = tmpav_lag_mean/wtmp_lag   

!surface runoff generated by snowmelt
   if(sub_snom(sb)==0. .or. sub_qd(sb)==0.) then
     sub_suro_snowmelt = 0.
   else
   sub_suro_snowmelt = sub_qd(sb)*sub_snom(sb)/(sub_snom(sb)+sub_subp(sb))     !! sub_qd(:)      |mm H2O        |surface runoff loading on day in subbasin
   end if                                                                         !! sub_subp(:)    |mm H2O        |precipitation for day in subbasin
                                                                               !! sub_snom(:)    |mm H2O        |amount of snow melt in subbasin on day   
!3 components in the sub_wtmp calculation
![1] surface runoff by snow melt, set as 0.1
![2] based flow, from input
![3] other flows, as Tair_av 

!for snowmelt-generated surface runoff 
!sub_wtmp(sb)=sub_suro_snowmelt*0.1*wtmp_alpha           
   sub_wtmp(sb) = sub_suro_snowmelt * wtmp_alpha           !! ------------------------------------------------------   
!sub_wtmp(sb)=sub_wtmp(sb)*2         ! added by Du calinration increase sonw melt temp to 0.2
!for baseflow

!gwtmp_ann=10.5
!sub_wtmp(sb)=sub_wtmp(sb)+sub_gwq(sb)*gwtmp_ann*wtmp_mu      
sub_wtmp(sb) = sub_wtmp(sb) + sub_gwq(sb)*wtmp_mu           !!------------------------------------------------------
!wtmp_gamma=1.1  ! calibration 
sub_wtmp(sb) = sub_wtmp(sb) + max(tmpav_lag_mean,-1.0)*(sub_wyld(sb)-sub_suro_snowmelt-sub_gwq(sb))*wtmp_gamma            !! sub_wyld(sb)--> qdr(j) 
                                                                                                                          !! sub_gwq(sb) --> gw_q(j)
                                                                                                                          !! sub_qd(sb) --> qday  
!sub_wtmp(sb)=sub_wtmp(sb)+tmpav_lag_mean*(sub_wyld(sb)-sub_suro_snowmelt-sub_gwq(sb))*wtmp_gamma
if(sub_wyld(sb)>0.000001) then
sub_wtmp(sb) = sub_wtmp(sb)/sub_wyld(sb)
else
sub_wtmp(sb) = 0.
endif 
!----------------------------------------------------------------------------------------------------------------------
!if (sub_wtmp(sb) <= 0.1) sub_wtmp(sb) = 0.1 !see "subwq"  ! disabled by Du
if (sub_wtmp(sb) <= -1.0) sub_wtmp(sb) = -1.0 !! modified by Du
!sub_wtmp_Ficklin = sub_wtmp(sb)

   if( sub_qd(sb) > 0.000001 ) then 
   sub_wtmp_surq(sb)= (max(tmpav_lag_mean,-1.0)*wtmp_gamma*(sub_qd(sb)-sub_suro_snowmelt) + sub_suro_snowmelt*wtmp_alpha)/ sub_qd(sb) !! mixing snowmelt and runoff 
   else
   sub_wtmp_surq(sb)= 0.
   end if
  
   if(sub_latq(sb) > 0.000001) then
   sub_wtmp_latq(sb)= max(tmpav_lag_mean,-1.0)*wtmp_gamma   
   else 
   sub_wtmp_latq(sb)= 0.
   end if
  
   if(sub_gwq(sb) > 0.000001) then
   sub_wtmp_gwq(sb)= wtmp_mu
   else
   sub_wtmp_gwq(sb)= 0.
   endif    
  
   if(sub_gwq_d(sb)  > 0.000001) then                   
   sub_wtmp_gwdp(sb)= wtmp_mu
   else
   sub_wtmp_gwdp(sb)= 0.
   endif
  
   if(sub_wtmp_surq(sb) <= -1.0) sub_wtmp_surq(sb)= -1.0
   if(sub_wtmp_latq(sb) <= -1.0) sub_wtmp_latq(sb)= -1.0
   if(sub_wtmp_gwq(sb) <= -1.0) sub_wtmp_gwq(sb)= -1.0   
   if(sub_wtmp_gwdp(sb) <= -1.0) sub_wtmp_gwdp(sb)= -1.0                

return

end 

